- name: Gathering network facts
  setup:
    gather_subset: '!all,!any,network'


- name: Assign a frontend IP address
  shell: "ip addr add {{ item }}/32 dev {{ frontend_ifname }}"
  loop: '{{ frontend_addresses }}'
  when: 'item not in ansible_all_ipv4_addresses '


- name: Install haproxy.cfg
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
  notify:
    - restart_haproxy


- name: Update sysctl
  sysctl: 
    name: net.ipv4.ip_nonlocal_bind
    value: 1
    reload: true
    state: present

