- name: Gathering network facts
  setup:
    gather_subset: '!all,!any,network'
  tags:
  - remove_frontend_ip
  - add_frontend_ip


- name: Assign a frontend IP address
  shell: "ip addr add {{ item }}/25 dev {{ frontend_ifname }}"
  loop: '{{ frontend_addresses }}'
  when: 'item not in ansible_all_ipv4_addresses '
  tags:
  - add_frontend_ip


- name: Detach an IP address(es)
  shell: "ip addr del {{ item }}/25 dev {{ frontend_ifname }} || true"
  loop: '{{ frontend_addresses }}'
  when: 'item in ansible_all_ipv4_addresses '
  tags: 
  - never
#  - remove_frontend_ips


- name: Disable SELinux
  selinux:
    policy: targeted
    state: disabled


- name: Install haproxy.cfg
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
  notify:
    - restart_haproxy
  tags:
    - add_frontend_ip
    - remove_frontend_ip


- name: Update sysctl
  sysctl: 
    name: net.ipv4.ip_nonlocal_bind
    value: 1
    reload: true
    state: present

